version: "3.7"
services:
  example:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: example
    ports:
      - "8080:8080"
#    volumes:
#      - logs:/apps/docker/logs
    env_file:
      - env
      - env.secrets
#    environment:
#      - DOCKER_HOST_IP=${DOCKER_HOST_IP}

